# Generated by Django 4.0.6 on 2022-10-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('Id_dieta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_dieta', models.CharField(max_length=40)),
                ('desc_dieta', models.CharField(max_length=120)),
                ('info_dieta', models.CharField(max_length=255)),
                ('duracion_dieta', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('Id_rutina', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rutina', models.CharField(max_length=40)),
                ('desc_rutina', models.CharField(max_length=120)),
                ('info_rutina', models.CharField(max_length=255)),
                ('dificultad', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.SmallIntegerField()),
                ('altura', models.SmallIntegerField()),
                ('peso', models.SmallIntegerField()),
                ('deporte', models.CharField(max_length=40)),
                ('enfermedades', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
