# Generated by Django 4.0.6 on 2022-10-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_dieta_desc_dieta_alter_dieta_info_dieta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='info_dieta',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='info_rutina',
        ),
        migrations.AddField(
            model_name='dieta',
            name='info_dieta1',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='dieta',
            name='info_dieta2',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='dieta',
            name='info_dieta3',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='info_rutina1',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='info_rutina2',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='info_rutina3',
            field=models.CharField(max_length=750, null=True),
        ),
    ]
