# Generated by Django 4.0.6 on 2022-10-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_dieta_info_dieta_remove_rutina_info_rutina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='recomendacion',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='recomendacion',
            field=models.CharField(max_length=750, null=True),
        ),
    ]
