# Generated by Django 4.0.6 on 2022-10-22 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_dieta_info_dieta2_alter_dieta_info_dieta3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutina',
            old_name='recomendacion',
            new_name='previo',
        ),
    ]
