# Generated by Django 4.0.6 on 2022-11-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.CharField(max_length=10),
        ),
    ]
