# Generated by Django 4.0.6 on 2022-11-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_contacto_avisos_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.CharField(max_length=20),
        ),
    ]
