# Generated by Django 4.0.6 on 2022-11-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_remove_contacto_avisos_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.SmallIntegerField()),
                ('altura', models.SmallIntegerField()),
                ('peso', models.SmallIntegerField()),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
    ]
